version: "2.1"

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
        depends_on:
            - php
    php:
        image: php:7-fpm
        volumes:
            - ./code:/code

